export const EMAIL_CHANGED = "email_changed"
export const PASS_CHANGED = "pass_changed"
export const LOGIN_USER_SUCCESS = "login_user_success"
export const LOGIN_USER_FAIL = "login_user_failed"
export const LOGIN_USER = "login_user"

export const EMPLOYEE_UPDATE = "employee_update"
export const EMPLOYEE_CREATE = "employee_create"
export const EMPLOYEE_CREATE_DONE = "employee_create_done"
export const EMPLOYEE_CREATE_FAILED = "employee_create_failed"
export const EMPLOYEE_FETCH_SUCCESS = "employee_fetch_success"
export const EMPLOYEE_SAVE_SUCCESS = "employee_save_success"